//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Euro.GmServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://devtest.bmk.com", ConfigurationName="GmServices.PartsWS")]
    public interface PartsWS {
        
        // CODEGEN: Parameter 'getPartPricingReturn' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getPartPricingReturn")]
        Euro.GmServices.getPartPricingResponse getPartPricing(Euro.GmServices.getPartPricingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Euro.GmServices.getPartPricingResponse> getPartPricingAsync(Euro.GmServices.getPartPricingRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://devtest.bmk.com")]
    public partial class PartDetail : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string part_numberField;
        
        private double msrpField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string part_number {
            get {
                return this.part_numberField;
            }
            set {
                this.part_numberField = value;
                this.RaisePropertyChanged("part_number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public double msrp {
            get {
                return this.msrpField;
            }
            set {
                this.msrpField = value;
                this.RaisePropertyChanged("msrp");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getPartPricing", WrapperNamespace="http://devtest.bmk.com", IsWrapped=true)]
    public partial class getPartPricingRequest {
        
        public getPartPricingRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getPartPricingResponse", WrapperNamespace="http://devtest.bmk.com", IsWrapped=true)]
    public partial class getPartPricingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://devtest.bmk.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("getPartPricingReturn")]
        public Euro.GmServices.PartDetail[] getPartPricingReturn;
        
        public getPartPricingResponse() {
        }
        
        public getPartPricingResponse(Euro.GmServices.PartDetail[] getPartPricingReturn) {
            this.getPartPricingReturn = getPartPricingReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PartsWSChannel : Euro.GmServices.PartsWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PartsWSClient : System.ServiceModel.ClientBase<Euro.GmServices.PartsWS>, Euro.GmServices.PartsWS {
        
        public PartsWSClient() {
        }
        
        public PartsWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PartsWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PartsWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PartsWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Euro.GmServices.getPartPricingResponse Euro.GmServices.PartsWS.getPartPricing(Euro.GmServices.getPartPricingRequest request) {
            return base.Channel.getPartPricing(request);
        }
        
        public Euro.GmServices.PartDetail[] getPartPricing() {
            Euro.GmServices.getPartPricingRequest inValue = new Euro.GmServices.getPartPricingRequest();
            Euro.GmServices.getPartPricingResponse retVal = ((Euro.GmServices.PartsWS)(this)).getPartPricing(inValue);
            return retVal.getPartPricingReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Euro.GmServices.getPartPricingResponse> Euro.GmServices.PartsWS.getPartPricingAsync(Euro.GmServices.getPartPricingRequest request) {
            return base.Channel.getPartPricingAsync(request);
        }
        
        public System.Threading.Tasks.Task<Euro.GmServices.getPartPricingResponse> getPartPricingAsync() {
            Euro.GmServices.getPartPricingRequest inValue = new Euro.GmServices.getPartPricingRequest();
            return ((Euro.GmServices.PartsWS)(this)).getPartPricingAsync(inValue);
        }
    }
}
